language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install -r requirements.txt
script: pytest --cov=ndtamr ndtamr/tests/
after_success:
  - coveralls
